import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { default as TitleBar } from "./navigation_bar/titleBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cyberpunk">
      <body className={manrope.className}>
        <div className="mt-2 mx-2 mb-4">
          <TitleBar />
        </div>
        <div className="flex flex-row w-screen h-screen">
          <div className="basis-1/4"></div>
          <div className="basis-3/4">{children}</div>
          <div className="basis-1/4"></div>
        </div>
      </body>
    </html>
  );
}
