import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { default as NavigationBar } from "./navigationBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cyberpunk">
      <body className={manrope.className}>
        <NavigationBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
